name: Android-Чтосмотреть-签到
on:
  workflow_dispatch:
  schedule:
    - cron: '1 5 * * *'
  watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【Android-Чтосмотреть-Daxilol】'
        run: |
          
          node Android-Чтосмотреть-Daxilol.js
        env:
          zqqdbody: ${{ secrets.zqqdbody }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
